"""
Type stubs for Wadjet native module (_wadjet).

𓆓 Wadjet-Link — Restoring the complete picture of the automotive stream.
"""

from typing import Iterator, List, Optional, Tuple, overload
from enum import IntEnum

# Version info
__version__: str
def version_string() -> str: ...
def version_major() -> int: ...
def version_minor() -> int: ...
def version_patch() -> int: ...

# Utilities
def bytes_to_hex(data: bytes) -> str: ...
def hex_to_bytes(hex_str: str) -> bytes: ...
def available_devices() -> List[str]: ...

# ---------------------------------------------------------------------------
# Core Types
# ---------------------------------------------------------------------------

class Timestamp:
    """High-precision timestamp with seconds and nanoseconds."""
    
    seconds: int
    nanoseconds: int
    
    def __init__(self, seconds: int = 0, nanoseconds: int = 0) -> None: ...
    @staticmethod
    def now() -> Timestamp: ...
    def total_nanoseconds(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Timestamp) -> bool: ...
    def __le__(self, other: Timestamp) -> bool: ...
    def __gt__(self, other: Timestamp) -> bool: ...
    def __ge__(self, other: Timestamp) -> bool: ...
    def __repr__(self) -> str: ...

class PacketView:
    """Immutable zero-copy view into packet data."""
    
    @property
    def timestamp(self) -> Timestamp: ...
    def __len__(self) -> int: ...
    def __bytes__(self) -> bytes: ...
    @overload
    def __getitem__(self, index: int) -> int: ...
    @overload
    def __getitem__(self, index: slice) -> PacketView: ...
    def hex(self) -> str: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Iterator[int]: ...
    # Buffer protocol support
    def __buffer__(self, flags: int) -> memoryview: ...

class Packet:
    """Mutable packet buffer with timestamp."""
    
    @property
    def timestamp(self) -> Timestamp: ...
    @timestamp.setter
    def timestamp(self, value: Timestamp) -> None: ...
    
    def __init__(self, data: bytes = b"") -> None: ...
    def __len__(self) -> int: ...
    def __bytes__(self) -> bytes: ...
    @overload
    def __getitem__(self, index: int) -> int: ...
    @overload
    def __getitem__(self, index: slice) -> PacketView: ...
    def view(self) -> PacketView: ...
    def hex(self) -> str: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Iterator[int]: ...
    # Buffer protocol support
    def __buffer__(self, flags: int) -> memoryview: ...

# ---------------------------------------------------------------------------
# Capture
# ---------------------------------------------------------------------------

class TimestampSource(IntEnum):
    """Timestamp source for packet capture."""
    SOFTWARE = 0
    HARDWARE = 1
    ADAPTER = 2

class CaptureSessionOptions:
    """Options for configuring a capture session."""
    
    promiscuous: bool
    snaplen: int
    timeout_ms: int
    buffer_size: int
    timestamp_source: TimestampSource
    
    def __init__(self) -> None: ...

class CaptureStats:
    """Statistics from a capture session."""
    
    packets_received: int
    packets_dropped: int
    packets_if_dropped: int
    
    def __repr__(self) -> str: ...

class CaptureSession:
    """Live packet capture session."""
    
    @staticmethod
    def create(interface: str, options: CaptureSessionOptions = ...) -> CaptureSession: ...
    def set_filter(self, filter_expr: str) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def next_packet(self, timeout_ms: int = 1000) -> Optional[Packet]: ...
    def stats(self) -> CaptureStats: ...
    def __iter__(self) -> Iterator[Packet]: ...

# ---------------------------------------------------------------------------
# PCAP I/O
# ---------------------------------------------------------------------------

class PcapReader:
    """PCAP file reader with context manager support."""
    
    @staticmethod
    def open(path: str) -> PcapReader: ...
    def read(self) -> Optional[Packet]: ...
    def __iter__(self) -> Iterator[Packet]: ...
    def __next__(self) -> Packet: ...
    def __enter__(self) -> PcapReader: ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> bool: ...

class PcapWriter:
    """PCAP file writer with context manager support."""
    
    @staticmethod
    def create(path: str, link_type: int = 1) -> PcapWriter: ...
    def write(self, packet: Packet) -> None: ...
    def __enter__(self) -> PcapWriter: ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> bool: ...

# ---------------------------------------------------------------------------
# Protocol Headers
# ---------------------------------------------------------------------------

class EthernetHeader:
    """Ethernet II header."""
    
    @property
    def dst_mac(self) -> Tuple[int, int, int, int, int, int]: ...
    @property
    def src_mac(self) -> Tuple[int, int, int, int, int, int]: ...
    @property
    def ethertype(self) -> int: ...
    
    def dst_mac_str(self) -> str: ...
    def src_mac_str(self) -> str: ...
    def __repr__(self) -> str: ...

class VlanTag:
    """802.1Q VLAN tag."""
    
    @property
    def priority(self) -> int: ...
    @property
    def dei(self) -> bool: ...
    @property
    def vlan_id(self) -> int: ...
    @property
    def ethertype(self) -> int: ...
    
    def __repr__(self) -> str: ...

class IPv4Header:
    """IPv4 header."""
    
    @property
    def version(self) -> int: ...
    @property
    def ihl(self) -> int: ...
    @property
    def dscp(self) -> int: ...
    @property
    def ecn(self) -> int: ...
    @property
    def total_length(self) -> int: ...
    @property
    def identification(self) -> int: ...
    @property
    def flags(self) -> int: ...
    @property
    def fragment_offset(self) -> int: ...
    @property
    def ttl(self) -> int: ...
    @property
    def protocol(self) -> int: ...
    @property
    def checksum(self) -> int: ...
    @property
    def src_ip(self) -> int: ...
    @property
    def dst_ip(self) -> int: ...
    
    def src_ip_str(self) -> str: ...
    def dst_ip_str(self) -> str: ...
    def header_length(self) -> int: ...
    def __repr__(self) -> str: ...

class UdpHeader:
    """UDP header."""
    
    @property
    def src_port(self) -> int: ...
    @property
    def dst_port(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def checksum(self) -> int: ...
    
    def __repr__(self) -> str: ...

class TcpHeader:
    """TCP header."""
    
    @property
    def src_port(self) -> int: ...
    @property
    def dst_port(self) -> int: ...
    @property
    def sequence_number(self) -> int: ...
    @property
    def acknowledgment_number(self) -> int: ...
    @property
    def data_offset(self) -> int: ...
    @property
    def flags(self) -> int: ...
    @property
    def window_size(self) -> int: ...
    @property
    def checksum(self) -> int: ...
    @property
    def urgent_pointer(self) -> int: ...
    
    def header_length(self) -> int: ...
    def is_syn(self) -> bool: ...
    def is_ack(self) -> bool: ...
    def is_fin(self) -> bool: ...
    def is_rst(self) -> bool: ...
    def is_psh(self) -> bool: ...
    def __repr__(self) -> str: ...

class MessageType(IntEnum):
    """SOME/IP message type."""
    REQUEST = 0x00
    REQUEST_NO_RETURN = 0x01
    NOTIFICATION = 0x02
    REQUEST_ACK = 0x40
    REQUEST_NO_RETURN_ACK = 0x41
    NOTIFICATION_ACK = 0x42
    RESPONSE = 0x80
    ERROR = 0x81
    RESPONSE_ACK = 0xC0
    ERROR_ACK = 0xC1
    TP_REQUEST = 0x20
    TP_REQUEST_NO_RETURN = 0x21
    TP_NOTIFICATION = 0x22
    TP_RESPONSE = 0xA0
    TP_ERROR = 0xA1

class ReturnCode(IntEnum):
    """SOME/IP return code."""
    E_OK = 0x00
    E_NOT_OK = 0x01
    E_UNKNOWN_SERVICE = 0x02
    E_UNKNOWN_METHOD = 0x03
    E_NOT_READY = 0x04
    E_NOT_REACHABLE = 0x05
    E_TIMEOUT = 0x06
    E_WRONG_PROTOCOL_VERSION = 0x07
    E_WRONG_INTERFACE_VERSION = 0x08
    E_MALFORMED_MESSAGE = 0x09
    E_WRONG_MESSAGE_TYPE = 0x0A

class SomeIpHeader:
    """SOME/IP header."""
    
    @property
    def service_id(self) -> int: ...
    @property
    def method_id(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def client_id(self) -> int: ...
    @property
    def session_id(self) -> int: ...
    @property
    def protocol_version(self) -> int: ...
    @property
    def interface_version(self) -> int: ...
    @property
    def message_type(self) -> MessageType: ...
    @property
    def return_code(self) -> ReturnCode: ...
    
    def is_request(self) -> bool: ...
    def is_response(self) -> bool: ...
    def is_notification(self) -> bool: ...
    def is_error(self) -> bool: ...
    def __repr__(self) -> str: ...

class SomeIpSdHeader:
    """SOME/IP Service Discovery header."""
    
    @property
    def flags(self) -> int: ...
    @property
    def reboot_flag(self) -> bool: ...
    @property
    def unicast_flag(self) -> bool: ...
    @property
    def entries_length(self) -> int: ...
    @property
    def options_length(self) -> int: ...
    
    def __repr__(self) -> str: ...

class PayloadType(IntEnum):
    """DoIP payload type."""
    GENERIC_NEGATIVE_ACK = 0x0000
    VEHICLE_IDENTIFICATION_REQUEST = 0x0001
    VEHICLE_IDENTIFICATION_REQUEST_EID = 0x0002
    VEHICLE_IDENTIFICATION_REQUEST_VIN = 0x0003
    VEHICLE_ANNOUNCEMENT = 0x0004
    ROUTING_ACTIVATION_REQUEST = 0x0005
    ROUTING_ACTIVATION_RESPONSE = 0x0006
    ALIVE_CHECK_REQUEST = 0x0007
    ALIVE_CHECK_RESPONSE = 0x0008
    ENTITY_STATUS_REQUEST = 0x4001
    ENTITY_STATUS_RESPONSE = 0x4002
    DIAGNOSTIC_POWER_MODE_REQUEST = 0x4003
    DIAGNOSTIC_POWER_MODE_RESPONSE = 0x4004
    DIAGNOSTIC_MESSAGE = 0x8001
    DIAGNOSTIC_MESSAGE_POSITIVE_ACK = 0x8002
    DIAGNOSTIC_MESSAGE_NEGATIVE_ACK = 0x8003

class DoIPHeader:
    """DoIP header."""
    
    @property
    def protocol_version(self) -> int: ...
    @property
    def inverse_protocol_version(self) -> int: ...
    @property
    def payload_type(self) -> PayloadType: ...
    @property
    def payload_length(self) -> int: ...
    @property
    def source_address(self) -> int: ...
    @property
    def target_address(self) -> int: ...
    
    def payload_type_value(self) -> int: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Decoding
# ---------------------------------------------------------------------------

class DecodeResult:
    """Result of decoding a packet through the protocol stack."""
    
    def has_ethernet(self) -> bool: ...
    def has_vlan(self) -> bool: ...
    def has_ipv4(self) -> bool: ...
    def has_udp(self) -> bool: ...
    def has_tcp(self) -> bool: ...
    def has_someip(self) -> bool: ...
    def has_someip_sd(self) -> bool: ...
    def has_doip(self) -> bool: ...
    
    def ethernet(self) -> Optional[EthernetHeader]: ...
    def vlan(self) -> Optional[VlanTag]: ...
    def ipv4(self) -> Optional[IPv4Header]: ...
    def udp(self) -> Optional[UdpHeader]: ...
    def tcp(self) -> Optional[TcpHeader]: ...
    def someip(self) -> Optional[SomeIpHeader]: ...
    def someip_sd(self) -> Optional[SomeIpSdHeader]: ...
    def doip(self) -> Optional[DoIPHeader]: ...
    def payload(self) -> bytes: ...
    
    def __repr__(self) -> str: ...

class ProtocolDispatcher:
    """Protocol decoder dispatcher."""
    
    def __init__(self) -> None: ...
    def decode(self, view: PacketView) -> DecodeResult: ...

def decode_packet(view: PacketView) -> DecodeResult:
    """Decode a packet view and return the result."""
    ...
